{{- if and (eq .Values.auth.mode "sharedSecret") (not .Values.auth.sharedSecret.existingSecret) -}}
{{- include "ami-mcp.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ami-mcp.sharedSecretName" . }}
  labels:
    {{- include "ami-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  shared-secret: {{ .Values.auth.sharedSecret.secretValue | quote }}
{{- end }}
